In [9]:
import pandas as pd
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.svm import SVC
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
import os

print(os.getcwd())

c:\Users\USER\OneDrive\Documents\7.ML\7.ML\5.SUPERVISED_ALG

In [11]:
os.listdir()

['1.DT_LAD.ipynb',
 '10.NAIVE_BAYES.ipynb',
 '2.RANDOM_LD.ipynb',
 '2i)RFC_Churn.ipynb',
 '2ii)RFR_data.ipynb',
 '3.titanic_Random.ipynb',
 '4.XGB_LAD.ipynb',
 '4i)XGBC_Telco.ipynb',
 '4ii)XGBR_insurance.ipynb',
 '5.KNN_loan.ipynb',
 '5i)KNN_TELCO.ipynb',
 '6.GSCV_LD(dectreeclasss).ipynb',
 '6i)GSCV_(Randomforest).ipynb',
 '6ii)GSCV_(logisticregression) .ipynb',
 '7.SVM_LD.ipynb',
 '7i).SVM_Vectorisation_senti.ipynb',
 '7ii).tweets.ipynb',
 'Churn_Modelling.csv',
 'data.csv',
 'insurance.csv',
 'loan_approval_dataset.csv.xls',
 'loan_data.csv.xls',
 'sentiment_data.csv',
 'telco_customer.csv',
 'titanic .csv',
 'Tweets.csv']

In [12]:
import os

print(os.path.exists("Tweets.csv"))

True

In [13]:
df = pd.read_csv("C:\\Users\\USER\\OneDrive\\Documents\\7.ML\\7.ML\\5.SUPERVISED_ALG\\Tweets.csv")
df

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14635,569587686496825344,positive,0.3487,NaN,0.0000,American,NaN,KristenReenders,NaN,0,@AmericanAir thank you we got on a different f...,NaN,2015-02-22 12:01:01 -0800,NaN,NaN
14636,569587371693355008,negative,1.0000,Customer Service Issue,1.0000,American,NaN,itsropes,NaN,0,@AmericanAir leaving over 20 minutes Late Flig...,NaN,2015-02-22 11:59:46 -0800,Texas,NaN
14637,569587242672398336,neutral,1.0000,NaN,NaN,American,NaN,sanyabun,NaN,0,@AmericanAir Please bring American Airlines to...,NaN,2015-02-22 11:59:15 -0800,"Nigeria,lagos",NaN
14638,569587188687634433,negative,1.0000,Customer Service Issue,0.6659,American,NaN,SraJackson,NaN,0,"@AmericanAir you have my money, you change my ...",NaN,2015-02-22 11:59:02 -0800,New Jersey,Eastern Time (US & Canada)
14639,569587140490866689,neutral,0.6771,NaN,0.0000,American,NaN,daviddtwu,NaN,0,@AmericanAir we have 8 ppl so we need 2 know h...,NaN,2015-02-22 11:58:51 -0800,"dallas, TX",NaN

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   tweet_id                      14640 non-null  int64
 1   airline_sentiment             14640 non-null  str
 2   airline_sentiment_confidence  14640 non-null  float64
 3   negativereason                9178 non-null   str
 4   negativereason_confidence     10522 non-null  float64
 5   airline                       14640 non-null  str
 6   airline_sentiment_gold        40 non-null     str
 7   name                          14640 non-null  str
 8   negativereason_gold           32 non-null     str
 9   retweet_count                 14640 non-null  int64
 10  text                          14640 non-null  str
 11  tweet_coord                   1019 non-null   str
 12  tweet_created                 14640 non-null  str
 13  tweet_location                9907 non-null   str
 14  user_timezone                 9820 non-null   str
dtypes: float64(2), int64(2), str(11)
memory usage: 4.4 MB

In [15]:
df.isnull().sum()

tweet_id                            0
airline_sentiment                   0
airline_sentiment_confidence        0
negativereason                   5462
negativereason_confidence        4118
airline                             0
airline_sentiment_gold          14600
name                                0
negativereason_gold             14608
retweet_count                       0
text                                0
tweet_coord                     13621
tweet_created                       0
tweet_location                   4733
user_timezone                    4820
dtype: int64

In [16]:
# keeping only required columns

df = df[["text","airline_sentiment"]]
df

                                                    text airline_sentiment
0                    @VirginAmerica What @dhepburn said.           neutral
1      @VirginAmerica plus you've added commercials t...          positive
2      @VirginAmerica I didn't today... Must mean I n...           neutral
3      @VirginAmerica it's really aggressive to blast...          negative
4      @VirginAmerica and it's a really big bad thing...          negative
...                                                  ...               ...
14635  @AmericanAir thank you we got on a different f...          positive
14636  @AmericanAir leaving over 20 minutes Late Flig...          negative
14637  @AmericanAir Please bring American Airlines to...           neutral
14638  @AmericanAir you have my money, you change my ...          negative
14639  @AmericanAir we have 8 ppl so we need 2 know h...           neutral

[14640 rows x 2 columns]

In [17]:
X = df.drop(columns="airline_sentiment")
y = df["airline_sentiment"]

In [18]:
df["airline_sentiment"].value_counts()

airline_sentiment
negative    9178
neutral     3099
positive    2363
Name: count, dtype: int64

In [19]:
xtrain, xtest, ytrain, ytest = train_test_split(X,y,train_size=0.8, random_state=42)

In [20]:
obj_cols = X.select_dtypes(include='object').columns

C:\Users\USER\AppData\Local\Temp\ipykernel_15024\2203036399.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = X.select_dtypes(include='object').columns

In [21]:
X[obj_cols].nunique()

text    14427
dtype: int64

# BEFORE PIPELINE

In [22]:
sample = [

        "I love football",

        "Worst flight experience",

        "The food was amazing"

]

In [23]:
cv = CountVectorizer()

In [24]:
result = cv.fit_transform(sample)
result

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9 stored elements and shape (3, 9)>

In [25]:
type(result)

scipy.sparse._csr.csr_matrix

In [26]:
cv.vocabulary_

{'love': 5,
 'football': 4,
 'worst': 8,
 'flight': 2,
 'experience': 1,
 'the': 6,
 'food': 3,
 'was': 7,
 'amazing': 0}

In [27]:
cv.get_feature_names_out()

array(['amazing', 'experience', 'flight', 'food', 'football', 'love',
       'the', 'was', 'worst'], dtype=object)

In [28]:
result

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9 stored elements and shape (3, 9)>

In [29]:
result.toarray()

array([[0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 1, 0, 0, 1, 1, 0]])

# COLUMN TRANSFORMER

In [30]:
preprocessing = ColumnTransformer(
        transformers=[
                ("count_vectorizer",
                 CountVectorizer(
                        stop_words="english",
                        lowercase=True
                        ),
                 "text")
                ],
        remainder="drop"
)

#  PIPELINE

In [31]:
main_pipeline = Pipeline(
            steps=[
                ("preprocessing",preprocessing),
                ("model",SVC())
            ]
)

In [32]:
grid_search_cv = GridSearchCV(
            estimator=main_pipeline,
            param_grid={
                "model__C":[0.1,1,10],
                "model__kernel":[
                            "linear",
                            "rbf"
                        ]},
            cv=5,
            verbose=1,
            n_jobs=-1
)

In [33]:
grid_search_cv.fit(xtrain,ytrain)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('count_vectorizer',
                                                                         CountVectorizer(stop_words='english'),
                                                                         'text')])),
                                       ('model', SVC())]),
             n_jobs=-1,
             param_grid={'model__C': [0.1, 1, 10],
                         'model__kernel': ['linear', 'rbf']},
             verbose=1)

In [34]:
grid_search_cv.best_params_

{'model__C': 10, 'model__kernel': 'rbf'}

In [35]:
grid_search_cv.best_estimator_

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('count_vectorizer',
                                                  CountVectorizer(stop_words='english'),
                                                  'text')])),
                ('model', SVC(C=10))])

In [36]:
ypred = grid_search_cv.predict(xtest)

In [37]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

    negative       0.85      0.89      0.87      1889
     neutral       0.62      0.56      0.59       580
    positive       0.74      0.67      0.70       459

    accuracy                           0.79      2928
   macro avg       0.73      0.71      0.72      2928
weighted avg       0.79      0.79      0.79      2928